name: jwnotifyer
description: Custom app to receive notification when new content is available on JW.ORG.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2 # For iOS UI
  url_launcher: ^6.1.0  # To redirect on a webpage
  flutter_background_service: ^2.0.0  # To create a background service
  path_provider: ^2.0.9 # To manage paths
  flutter_local_notifications: ^9.5.2 # Notifications
  requests: ^4.2.1  # HTTP requests
  html: ^0.15.0 # To parse html content
  restart_app: ^1.1.0 # To restart the application in the function deleteAllContent()
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  



  flutter_lints: ^1.0.0 # Encourage good coding practices


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen/Oxygen-Regular.ttf
        - asset: fonts/Oxygen/Oxygen-Bold.ttf
          weight: 700
        - asset: fonts/Oxygen/Oxygen-Light.ttf
          weight: 300